# modules.translate

from disnake import Message, ApplicationCommandInteraction, ModalInteraction, MessageCommandInteraction, TextInputStyle, ui
from modules.utils.commons import send_long_message, pull_history_lines
from llama_index.core.output_parsers import PydanticOutputParser
from llama_index.llms.google_genai import GoogleGenAI
from pydantic import BaseModel, ValidationError
from typing import Dict, List, Set
from modules.utils import database
from asyncio import Queue, sleep
from disnake.ext import commands
from core import config
import asyncio
import logging
import disnake

class _TranslationSchema(BaseModel):
    translations: Dict[str, str]

class _Translator:
    def __init__(self) -> None:
        api_key = config.read().get("GOOGLE_API_KEY")
        if not api_key:
            raise RuntimeError("Google API key missing from configuration")
        self._llm = GoogleGenAI(model_name="gemini-2.0-flash", api_key=api_key)
        self._parser = PydanticOutputParser(_TranslationSchema)
        self._fmt_instructions = self._parser.get_format_string()

    async def translate(self, prompt: str) -> Dict[str, str]:
        full_prompt = f"{prompt}\n\n{self._fmt_instructions}"
        try:
            if hasattr(self._llm, "acomplete"):
                response = await self._llm.acomplete(full_prompt)
            else:
                response = await asyncio.to_thread(self._llm.complete, full_prompt)
            raw = getattr(response, "text", str(response))
            parsed: _TranslationSchema = self._parser.parse(raw)
            return parsed.translations
        except ValidationError as ve:
            logging.error("Translator JSON validation error: %s\nRaw: %s", ve, raw)
            raise
        except Exception:
            logging.exception("Translator unexpected error")
            raise

_translator = _Translator()

def _format_language_name(lang: str) -> str:
    return " ".join(word.capitalize() for word in lang.split())

def _build_prompt(history_lines: List[str], target_langs: Set[str], content: str) -> str:
    system_rules = (
        "You are a translation assistant. Your job is to:\n"
        "1. Translate messages while maintaining context, nuance and accuracy\n"
        "2. Never add commentary or additional messages\n"
        "3. Always use full language names\n"
        "4. Return translations ONLY as a valid JSON object containing a single key 'translations', which maps lowercase language names to translated text."
    )
    parts: List[str] = [system_rules]
    parts.extend(history_lines)
    targets = ", ".join(_format_language_name(t) for t in target_langs)
    parts.append(
        f"Translate this message to {targets}:\n{content}"
    )
    return "\n".join(parts)

def _create_embed(original_text: str, translations: Dict[str, str], auto: bool = True) -> str:
    sections: List[str] = []
    if not auto:
        sections.append("Original:\n" + "\n".join(f"> {line}" for line in original_text.split("\n")))
    for lang, text in translations.items():
        if not text.strip():
            continue
        sections.append(
            f"**{_format_language_name(lang)}:**\n" + "\n".join(f"> {line}" for line in text.split("\n"))
        )
    joined = "\n\n".join(sections)
    return f"{joined}\n\n-# ⚠️ These translations were generated by an AI language model and may not be perfectly accurate."

class TranslationCog(commands.Cog):
    def __init__(self, bot: commands.Bot):
        self.bot = bot
        self._queue: Queue = Queue()
        self._workers: list[asyncio.Task] = []

    async def cog_load(self):
        loop = asyncio.get_running_loop()
        self._workers = [loop.create_task(self._worker()) for _ in range(3)]

    async def _translate(self, content: str, msg_or_inter, target_langs: Set[str]) -> Dict[str, str]:
        if not content.strip():
            return {}
        if isinstance(msg_or_inter, Message) and msg_or_inter.mentions:
            for m in msg_or_inter.mentions:
                content = (
                    content.replace(f"<@{m.id}>", m.display_name).replace(f"<@!{m.id}>", m.display_name)
                )
        history = await pull_history_lines(msg_or_inter.channel, 7)
        prompt = _build_prompt(history, target_langs, content)
        translations = await _translator.translate(prompt)
        return {
            lang.lower(): text
            for lang, text in translations.items()
            if text.strip() and text.strip() != content.strip()
        }

    async def _worker(self):
        while True:
            try:
                message, target_langs = await self._queue.get()
                try:
                    if (
                        message.channel.locked
                        or not message.content.strip()
                    ):
                        continue
                    translations = await self._translate(message.content, message, target_langs)
                    if translations:
                        response = _create_embed(message.content, translations)
                        await send_long_message(message, response, should_reply=True)
                except Exception:
                    logging.exception("Translation worker error")
                finally:
                    self._queue.task_done()
            except asyncio.CancelledError:
                break
            except Exception:
                logging.exception("Worker fatal error")
                await sleep(1)

    @commands.Cog.listener()
    async def on_message(self, message: Message):
        if (
            message.author.bot
            or not isinstance(message.channel, disnake.Thread)
        ):
            return
        langs = set(await database.get_thread_languages(message.channel.id) or [])
        if not langs:
            return
        await self._queue.put((message, langs))

    @commands.slash_command(name="translate", description="Translate custom text via a modal")
    async def translate_root(self, inter: ApplicationCommandInteraction):
        modal = ui.Modal(
            title="Translate Text",
            custom_id="translate_modal",
            components=[
                ui.TextInput(
                    label="Text to translate",
                    custom_id="text_to_translate",
                    style=TextInputStyle.paragraph,
                    max_length=1000,
                ),
                ui.TextInput(
                    label="Target language(s) (comma separated)",
                    custom_id="target_language",
                    style=TextInputStyle.short,
                    max_length=100,
                ),
            ],
        )
        await inter.response.send_modal(modal)

    @commands.slash_command(name="autotranslate", description="Manage auto-translation languages (auto-translation is active when languages are set)")
    async def autotranslate(self, inter: ApplicationCommandInteraction):
        pass

    @autotranslate.sub_command(name="add", description="Add a language to this thread")
    async def at_add_language(self, inter: ApplicationCommandInteraction, language: str):
        if not isinstance(inter.channel, disnake.Thread):
            return await inter.response.send_message("❌ Use this in a thread", ephemeral=True)
        await database.add_thread_language(inter.channel.id, language.lower().strip())
        await inter.response.send_message(f"✅ Added {_format_language_name(language)} to this thread", ephemeral=False)

    @autotranslate.sub_command(name="remove", description="Remove a language from this thread")
    async def at_remove_language(self, inter: ApplicationCommandInteraction, language: str):
        if not isinstance(inter.channel, disnake.Thread):
            return await inter.response.send_message("❌ Use this in a thread", ephemeral=True)
        await database.remove_thread_language(inter.channel.id, language.lower().strip())
        await inter.response.send_message(f"🗑️ Removed {_format_language_name(language)} from this thread", ephemeral=False)

    @autotranslate.sub_command(name="status", description="Show current auto-translation status")
    async def at_status(self, inter: ApplicationCommandInteraction):
        if not isinstance(inter.channel, disnake.Thread):
            return await inter.response.send_message("❌ Use this in a thread", ephemeral=True)
        languages = await database.get_thread_languages(inter.channel.id) or []
        if not languages:
            await inter.response.send_message("🌐 Auto-translation is **disabled** (no target languages set)", ephemeral=True)
        else:
            lang_list = ", ".join(_format_language_name(lang) for lang in languages)
            await inter.response.send_message(f"🌐 Auto-translation is **enabled** for: {lang_list}", ephemeral=True)

    @commands.message_command(name="Translate")
    async def translate_context_menu(self, inter: MessageCommandInteraction, message: Message):
        if message.author.bot or not message.content.strip():
            return await inter.response.send_message("Nothing to translate.", ephemeral=True)
        modal = ui.Modal(
            title="Translate Message",
            custom_id=f"context_translate:{message.id}",
            components=[
                ui.TextInput(
                    label="Target language(s) (comma separated)",
                    custom_id="target_language",
                    style=TextInputStyle.short,
                    required=True,
                    max_length=100,
                )
            ],
        )
        await inter.response.send_modal(modal)

    @commands.Cog.listener("on_modal_submit")
    async def handle_modal(self, inter: ModalInteraction):
        if inter.custom_id == "translate_modal":
            await self._process_manual_translation(inter)
        elif inter.custom_id.startswith("context_translate:"):
            msg_id = int(inter.custom_id.split(":", 1)[1])
            msg = await inter.channel.fetch_message(msg_id)
            await self._process_manual_translation(inter, msg)

    async def _process_manual_translation(self, inter: ModalInteraction, original_msg: Message | None = None):
        await inter.response.defer()
        target_langs = {t.strip().lower() for t in inter.text_values["target_language"].split(",") if t.strip()}
        content = (
            original_msg.content if original_msg else inter.text_values["text_to_translate"]
        )
        translations = await self._translate(content, original_msg or inter, target_langs)
        if not translations:
            return await inter.edit_original_response("Translation failed or produced no output.")
        embed = _create_embed(content, translations, auto=False)
        await inter.edit_original_response(content=embed)

    def cog_unload(self):
        for t in self._workers:
            t.cancel()

def setup(bot):
    bot.add_cog(TranslationCog(bot))